name: Deploy to Environment

on:
  push:
    branches:
      - DEV_BRANCH

  workflow_dispatch:

env:
  COA_VERSION: 7.31.3

jobs:
  deploy-dev:
    name: Deploy to DEV
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22.19.0

      # Write DEV config
      - run: echo '${{ secrets.COA_CONFIG }}' > COA_CONFIG

      - run: npm list | grep "@coalescesoftware/coa@${{ env.COA_VERSION }}" || npm install @coalescesoftware/coa@${{ env.COA_VERSION }}

      - run: npx coa --version

      - run: npx coa plan --config COA_CONFIG --out ./coa-plan --debug

      - run: npx coa deploy --config COA_CONFIG --plan ./coa-plan --debug


  deploy-qa:
    name: Deploy to QA
    runs-on: ubuntu-latest

    # 👇 This ensures QA runs ONLY if DEV succeeds
    needs: deploy-dev

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22.19.0

      # Write QA config
      - run: echo '${{ secrets.COA_CONFIG_QA }}' > COA_CONFIG

      - run: npm list | grep "@coalescesoftware/coa@${{ env.COA_VERSION }}" || npm install @coalescesoftware/coa@${{ env.COA_VERSION }}

      - run: npx coa --version

      - run: npx coa plan --config COA_CONFIG --out ./coa-plan --debug

      - run: npx coa deploy --config COA_CONFIG --plan ./coa-plan --debug
