name: QA Deployment

on:
  workflow_dispatch: 

jobs:
  deploy-qa:
    runs-on: ubuntu-latest
    environment: QA_ENV 

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22.19.0

      - run: echo '${{ secrets.COA_CONFIG_QA }}' > COA_CONFIG
      - run: npm install @coalescesoftware/coa@7.31.3
      - run: npx coa deploy --config COA_CONFIG --plan ./coa-plan --debug
