name: QA Deployment

on:
  push:
    branch: QA_BRANCH

jobs:
  deploy-qa:
    # ✅ Run only if DEV succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    environment: QA_ENV

    steps:
      - uses: actions/checkout@v6
        with:
          ref: QA_BRANCH   # 👈 deploy from QA branch

      - uses: actions/setup-node@v6
        with:
          node-version: 22.19.0

      - run: echo '${{github.event.workflow_run.head_branch}}'
      
      - run: echo '${{ secrets.COA_CONFIG_QA }}' > COA_CONFIG

      - run: npm install @coalescesoftware/coa@7.31.3

      - run: npx coa plan --config COA_CONFIG --out ./coa-plan --debug

      - run: npx coa deploy --config COA_CONFIG --plan ./coa-plan --debug
